apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: uma-enhub-namespace-viewer
  labels:
    app.kubernetes.io/managed-by: config-sync
rules:
  - apiGroups: [""]
    resources: ["namespaces", "pods", "services"]
    verbs: ["get", "list", "watch"]
